# Generated by Django 4.0.6 on 2023-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=256)),
                ('emp_id', models.CharField(max_length=256)),
                ('com_name', models.CharField(max_length=256)),
                ('emp_email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('emp_address', models.CharField(max_length=256)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
