# Generated by Django 4.0.6 on 2023-10-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
