# Generated by Django 4.0.6 on 2023-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondApp', '0002_alter_employeedetails_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=12)),
                ('confirm_password', models.CharField(max_length=12)),
            ],
        ),
    ]
